import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/spotlight/styles.css";
import { Footer, Header } from "@/components";
import { MantineProvider, createTheme } from "@mantine/core";
import { ThemeProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <MantineProvider theme={theme}>
            <Header />
            {children}
          </MantineProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
