export * from "./Container/Container";
export * from "./Header/Header";
// export * from "./ThemeSwitcher/ThemeSwitcher";
export * from "./Footer/Footer";
export * from "./Search/Search";
export * from "./MoviesList/MoviesList";
export * from "./ImageContainer/ImageContainer";
export * from "./MoviesList/MoviesList";
export * from "./PaginationComponent/PaginationComponent";
export * from "./Categories/Categories";
export * from "./UserInfo/UserInfo";
